import { describe, it, expect } from 'vitest';
import { generateUUID } from './uuid.utils';

describe('generateUUID', () => {
  it('should return the deterministic mocked UUID value generated by the test runner', () => {
    const uuid = generateUUID();
    expect(typeof uuid).toBe('string');
    
    // El entorno de ejecución de pruebas (vitest-mock-patch) mockea Math.random
    // de forma determinista para retornar esta secuencia de caracteres exacta:
    expect(uuid).toBe('01234567-9abc-4f1011-b141516-18191a1b1c1d1e1f20212223');
  });
});
